language: python
sudo: required
dist: bionic
python:
    - 'nightly'
    - '3.8'
    - '3.7'
    - '3.6'
    - '3.5'
    - '2.7'
    - 'pypy'
    - 'pypy3'
install:
    - pip install cython pysam requests coverage pyfasta pyvcf numpy
    - pip install biopython || true
    - python setup.py install
    - if [ ! -f samtools-1.2 ]; then curl -sL https://github.com/samtools/samtools/releases/download/1.2/samtools-1.2.tar.bz2 | tar -xjv; fi
    - cd samtools-1.2
    - make
    - export PATH=$PATH:$PWD
    - cd ..
    - if [ ! -f htslib-1.4 ]; then curl -sL https://github.com/samtools/htslib/releases/download/1.4/htslib-1.4.tar.bz2 | tar -xjv; fi
    - cd htslib-1.4
    - make
    - export PATH=$PATH:$PWD
    - cd ..
before_script:
    - env pip install biopython
    - env python tests/data/download_gene_fasta.py
script: nosetests --with-coverage --cover-package=pyfaidx
deploy:
  provider: pypi
  user: mdshw5
  password:
    secure: MbSaeuitkVTZqxa0PJ3RcR1aMf+B/sMbcx2sWOo9xfLlRFDFpYWJZ0EfXWEhrVu2YWXpBsasgunTDWSi0jNcZMH92MzOC+UTVYr45LO5sy6hm4iSiAgm/DPgYWdjP0SFKr7eL/HWPS+gHvgkXL1upleX21O358bxaezoasuKFvs=
  on:
    all_branches: true
    python: 3.8
    tags: true
    repo: mdshw5/pyfaidx
matrix:
  include:
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
  allow_failures:
    - python: nightly
    - python: pypy3
    - python: pypy
    - os: windows
  fast_finish: true
cache:
    directories:
        - tests/data
        - samtools-1.2
        - htslib-1.4
after_success:
    - bash <(curl -s https://codecov.io/bash)

